### ISSUE TITLE
方法执行没有报错，但核心代码去哪了？

### ISSUE THREAD

**Issue by TestopB** [davinci1012/pinduoduo_backdoor_unpacker#12]
![image](https://user-images.githubusercontent.com/127718991/224620930-a8016bec-7044-42e8-a4ef-fb3657abd33f.png)

**Comment by icew4y** [comment]
大佬，请问如何利用复现这个漏洞？

**Comment by larboy1991** [comment]
全部代码打包压缩成jar，然后使用jadx打开
