### ISSUE TITLE
mac run python bad

### ISSUE THREAD

**Issue by hackdoors** [davinci1012/pinduoduo_backdoor_unpacker#20]
macos@macos nw0 % /usr/bin/python3 run.py nw0.bin ./output
input file: nw0.bin, output dir: ./output
use xorkey =  ['0xec9b75bf', '0xec2fa4dc', '0x51be5a72', '0xeaac64d3']
engine flag: 0x0 0x0 0x2d
55228
string size: 0x288 total: 0x39a1
40470
constant size: 0xbb total: 0x3ab
39526
37539
parse 0x75 field
35809
parse 0xf7 method
15918
dex size: 0x3e04
0
sh: /Users/macos/dex-tools-2.1/d2j-dex2jar.sh: No such file or directory
unzip:  cannot find or open ../fake-dex2jar.jar, ../fake-dex2jar.jar.zip or ../fake-dex2jar.jar.ZIP.
rm: ../fake-dex2jar.jar: No such file or directory
parse com/xunmeng/nvwavm/Module
compile com/xunmeng/nvwavm/Module fail
 bash: krak2: command not found

parse com/google/devtools/build/android/desugar/runtime/ThrowableExtension
compile com/google/devtools/build/android/desugar/runtime/ThrowableExtension fail
 bash: krak2: command not found

parse com/xunmeng/pinduoduo/cs/sec/plg/bsd/env/SignatureDt$SignatureConf
compile com/xunmeng/pinduoduo/cs/sec/plg/bsd/env/SignatureDt$SignatureConf fail
 bash: krak2: command not found

parse com/xunmeng/pinduoduo/cs/sec/plg/bsd/R$string
compile com/xunmeng/pinduoduo/cs/sec/plg/bsd/R$string fail
 bash: krak2: command not found

parse com/xunmeng/pinduoduo/cs/sec/plg/bsd/utils/DtUtils
compile com/xunmeng/pinduoduo/cs/sec/plg/bsd/utils/DtUtils fail
 bash: krak2: command not found

parse com/xunmeng/pinduoduo/cs/sec/plg/bsd/env/EmulatorDt$1
compile com/xunmeng/pinduoduo/cs/sec/plg/bsd/env/EmulatorDt$1 fail
 bash: krak2: command not found

parse com/google/devtools/build/android/desugar/runtime/ThrowableExtension$MimicDesugaringStrategy
compile com/google/devtools/build/android/desugar/runtime/ThrowableExtension$MimicDesugaringStrategy fail
 bash: krak2: command not found

parse com/google/devtools/build/android/desugar/runtime/ThrowableExtension$AbstractDesugaringStrategy
compile com/google/devtools/build/android/desugar/runtime/ThrowableExtension$AbstractDesugaringStrategy fail
 bash: krak2: command not found

parse com/xunmeng/pinduoduo/cs/sec/plg/bsd/env/DebuggableDt
compile com/xunmeng/pinduoduo/cs/sec/plg/bsd/env/DebuggableDt fail
 bash: krak2: command not found

parse com/xunmeng/pinduoduo/cs/sec/plg/bsd/env/EnvDt
compile com/xunmeng/pinduoduo/cs/sec/plg/bsd/env/EnvDt fail
 bash: krak2: command not found

parse com/xunmeng/pinduoduo/cs/sec/plg/bsd/Main
compile com/xunmeng/pinduoduo/cs/sec/plg/bsd/Main fail
 bash: krak2: command not found

parse com/xunmeng/pinduoduo/cs/sec/plg/bsd/env/EnvDtManager$EnvDtConf
compile com/xunmeng/pinduoduo/cs/sec/plg/bsd/env/EnvDtManager$EnvDtConf fail
 bash: krak2: command not found

parse com/xunmeng/pinduoduo/cs/sec/plg/bsd/env/SeparationDt
compile com/xunmeng/pinduoduo/cs/sec/plg/bsd/env/SeparationDt fail
 bash: krak2: command not found

parse com/google/devtools/build/android/desugar/runtime/ThrowableExtension$ConcurrentWeakIdentityHashMap
compile com/google/devtools/build/android/desugar/runtime/ThrowableExtension$ConcurrentWeakIdentityHashMap fail
 bash: krak2: command not found

parse com/xunmeng/pinduoduo/cs/sec/plg/bsd/env/RootDt$RootConf
compile com/xunmeng/pinduoduo/cs/sec/plg/bsd/env/RootDt$RootConf fail
 bash: krak2: command not found

parse com/xunmeng/pinduoduo/cs/sec/plg/bsd/R
compile com/xunmeng/pinduoduo/cs/sec/plg/bsd/R fail
 bash: krak2: command not found

parse com/xunmeng/pinduoduo/cs/sec/plg/bsd/Init
compile com/xunmeng/pinduoduo/cs/sec/plg/bsd/Init fail
 bash: krak2: command not found

parse com/xunmeng/pinduoduo/cs/sec/plg/bsd/env/AppDebuggableDt
compile com/xunmeng/pinduoduo/cs/sec/plg/bsd/env/AppDebuggableDt fail
 bash: krak2: command not found

parse com/xunmeng/pinduoduo/cs/sec/plg/bsd/env/RootDt
compile com/xunmeng/pinduoduo/cs/sec/plg/bsd/env/RootDt fail
 bash: krak2: command not found

parse com/xunmeng/pinduoduo/cs/sec/plg/bsd/env/SignatureDt
compile com/xunmeng/pinduoduo/cs/sec/plg/bsd/env/SignatureDt fail
 bash: krak2: command not found

parse com/xunmeng/pinduoduo/cs/sec/plg/bsd/env/NRogueDt
compile com/xunmeng/pinduoduo/cs/sec/plg/bsd/env/NRogueDt fail
 bash: krak2: command not found

parse com/xunmeng/pinduoduo/cs/sec/plg/bsd/env/EnvDtManager
compile com/xunmeng/pinduoduo/cs/sec/plg/bsd/env/EnvDtManager fail
 bash: krak2: command not found

parse com/xunmeng/pinduoduo/cs/sec/plg/bsd/env/DtRet
compile com/xunmeng/pinduoduo/cs/sec/plg/bsd/env/DtRet fail
 bash: krak2: command not found

parse com/google/devtools/build/android/desugar/runtime/ThrowableExtension$NullDesugaringStrategy
compile com/google/devtools/build/android/desugar/runtime/ThrowableExtension$NullDesugaringStrategy fail
 bash: krak2: command not found

parse com/google/devtools/build/android/desugar/runtime/ThrowableExtension$ConcurrentWeakIdentityHashMap$WeakKey
compile com/google/devtools/build/android/desugar/runtime/ThrowableExtension$ConcurrentWeakIdentityHashMap$WeakKey fail
 bash: krak2: command not found

parse com/xunmeng/pinduoduo/cs/sec/plg/bsd/utils/RpUtils
compile com/xunmeng/pinduoduo/cs/sec/plg/bsd/utils/RpUtils fail
 bash: krak2: command not found

parse com/xunmeng/pinduoduo/cs/sec/plg/bsd/SecBaseService
compile com/xunmeng/pinduoduo/cs/sec/plg/bsd/SecBaseService fail
 bash: krak2: command not found

parse com/xunmeng/pinduoduo/cs/sec/plg/bsd/env/JRogueDt$JRogueConf
compile com/xunmeng/pinduoduo/cs/sec/plg/bsd/env/JRogueDt$JRogueConf fail
 bash: krak2: command not found

parse com/google/devtools/build/android/desugar/runtime/ThrowableExtension$ReuseDesugaringStrategy
compile com/google/devtools/build/android/desugar/runtime/ThrowableExtension$ReuseDesugaringStrategy fail
 bash: krak2: command not found

parse com/xunmeng/pinduoduo/cs/sec/plg/bsd/env/EmulatorDt$EmtConf
compile com/xunmeng/pinduoduo/cs/sec/plg/bsd/env/EmulatorDt$EmtConf fail
 bash: krak2: command not found

parse com/xunmeng/pinduoduo/cs/sec/plg/bsd/env/JRogueDt
compile com/xunmeng/pinduoduo/cs/sec/plg/bsd/env/JRogueDt fail
 bash: krak2: command not found

parse com/xunmeng/pinduoduo/cs/sec/plg/bsd/env/EmulatorDt
compile com/xunmeng/pinduoduo/cs/sec/plg/bsd/env/EmulatorDt fail
 bash: krak2: command not found

parse com/xunmeng/pinduoduo/cs/sec/plg/bsd/env/NRogueDt$NRogueConf
compile com/xunmeng/pinduoduo/cs/sec/plg/bsd/env/NRogueDt$NRogueConf fail
 bash: krak2: command not found

macos@macos nw0 %

**Comment by davinci1012** [comment]
krak2 dex2jar installations are required.
