### ISSUE TITLE
请益：StartAnyWhere 和 System-Only API 之间的关系——如何构建一个具有 System 特权的 Context？

### ISSUE THREAD

**Issue by Konjac-XZ** [davinci1012/pinduoduo_backdoor_unpacker#27]
-- Removed -- 
感谢楼下大佬指正，安全意识还是欠缺。

**Comment by davinci2023fans** [comment]
1. LaunchAnyWhere一个很重要的能力是进一步通过grantUriPermission和FileProvider读写私有文件，进而执行代码。这个很重要的环节你漏掉了，显然不是你说的所谓只能“恶作剧”。
2. 在第一个的基础上，pdd通过这个方式覆盖system app的文件，进而执行代码。你后面看到的都是在特权app里执行的。所以这个链条是：
```
StartAnyWhere → 通过恶意 Intent 读取系统App的FileProvider->覆盖系统App的动态代码文件，注入后门执行代码->获取到一个具有系统签名的 Context → 通过 Context 和反射执行系统方法
```

**Comment by Konjac-XZ** [comment]
> 1. LaunchAnyWhere 一个很重要的能力是进一步通过 grantUriPermission 和 FileProvider 读写私有文件，进而执行代码。这个很重要的环节你漏掉了，显然不是你说的所谓只能 “恶作剧”。
> 2. 在第一个的基础上，pdd 通过这个方式覆盖 system app 的文件，进而执行代码。你后面看到的都是在特权 app 里执行的。所以这个链条是：
> 
> ```
> StartAnyWhere → 通过恶意 Intent 读取系统App的FileProvider->覆盖系统App的动态代码文件，注入后门执行代码->获取到一个具有系统签名的 Context → 通过 Context 和反射执行系统方法
> ```

感谢前辈，给您磕头了，砰砰砰。
看到有人专门开个小号来回答我的问题才知道这个话题多么敏感。

**Comment by davinci2023fans** [comment]
> > 1. LaunchAnyWhere 一个很重要的能力是进一步通过 grantUriPermission 和 FileProvider 读写私有文件，进而执行代码。这个很重要的环节你漏掉了，显然不是你说的所谓只能 “恶作剧”。
> > 2. 在第一个的基础上，pdd 通过这个方式覆盖 system app 的文件，进而执行代码。你后面看到的都是在特权 app 里执行的。所以这个链条是：
> > 
> > ```
> > StartAnyWhere → 通过恶意 Intent 读取系统App的FileProvider->覆盖系统App的动态代码文件，注入后门执行代码->获取到一个具有系统签名的 Context → 通过 Context 和反射执行系统方法
> > ```
> 
> 感谢前辈，给您磕头了，砰砰砰。 看到有人专门开个小号来回答我的问题才知道这个话题多么敏感。

不敏感，也不应该敏感。它们才是应该感到害怕的。
