### ISSUE TITLE
解包成功【中间未报错】，但是class反编译内容都失败

### ISSUE THREAD

**Issue by lauhwong** [davinci1012/pinduoduo_backdoor_unpacker#5]
RT

**Comment by jas502n** [comment]
https://github.com/mstrobel/procyon/releases

要使用Procyon反编译一个JAR文件并将结果保存到名为`output`的文件夹中，可以使用以下命令：

```bash
$ java -jar procyon-decompiler-X.X.jar -o output YourJarFile.jar
```

其中，`procyon-decompiler-X.X.jar` 是您下载并安装的Procyon反编译器的文件名和路径，`YourJarFile.jar` 是您要反编译的JAR文件的文件名和路径，`-o output` 指定将反编译结果输出到名为 `output` 的文件夹中。

**Comment by davinci1012** [comment]
Use jadx
