### ISSUE TITLE
成功获取到代码，多谢大佬

### ISSUE THREAD

**Issue by MortonSun** [davinci1012/pinduoduo_backdoor_unpacker#6]
成功获取到代码，但是我看没人放出来呢，是不是都怕被盯上？

**Comment by Morris-Mao** [comment]
哥哥分享下

**Comment by poorjobless** [comment]
> 哥哥分享下

https://github.com/poorjobless/pinduoduo_backdoor_code

**Comment by A-new** [comment]
> > 哥哥分享下
> 
> https://github.com/poorjobless/pinduoduo_backdoor_code
大佬能不能介绍一下怎么提取用脱壳代码提取不？
